project:
  type: website

website:
  title: "Yajun Liu"
  navbar:
    left:
      - href: index.qmd
        text: homepage
      - about.qmd
      - teaching.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

